#define MAT_NONE 0
#define MAT_LABPBR 1
#define MAT_OLDPBR 2

#define LIGHT_MODE_VANILLA 0
#define LIGHT_MODE_LPV 1
#define LIGHT_MODE_RT 2

#define REFLECT_MODE_NONE 0
#define REFLECT_MODE_SSR 1
#define REFLECT_MODE_WSR 2

#define DEBUG_VIEW_NONE 0
#define DEBUG_VIEW_MATERIAL 1
#define DEBUG_VIEW_SHADOWS 2
#define DEBUG_VIEW_SSS 3
#define DEBUG_VIEW_SSAO 4
#define DEBUG_VIEW_SSGI 5
#define DEBUG_VIEW_VL 6
#define DEBUG_VIEW_SKY_IRRADIANCE 7
#define DEBUG_VIEW_SHADOWMAP_COLOR 8
#define DEBUG_VIEW_SHADOWMAP_NORMAL 9

#define DEBUG_MAT_NONE 0
#define DEBUG_MAT_ALBEDO 1
#define DEBUG_MAT_GEO_NORMAL 2
#define DEBUG_MAT_TEX_NORMAL 3
#define DEBUG_MAT_OCCLUSION 4
#define DEBUG_MAT_ROUGH 5
#define DEBUG_MAT_F0_METAL 6
#define DEBUG_MAT_POROSITY 7
#define DEBUG_MAT_SSS 8
#define DEBUG_MAT_EMISSION 9
#define DEBUG_MAT_LMCOORD 10
