#define MAT_NONE 0
#define MAT_LABPBR 1
#define MAT_OLDPBR 2

#define POM_TYPE_NONE 0
#define POM_TYPE_SHARP 1
#define POM_TYPE_SMOOTH 2

#define LIGHT_MODE_VANILLA 0
#define LIGHT_MODE_LPV 1
#define LIGHT_MODE_RT 2
#define LIGHT_MODE_SHADOWS 3

#define REFLECT_MODE_NONE 0
#define REFLECT_MODE_SSR 1
#define REFLECT_MODE_WSR 2

#define BLOCK_HAND 65550

#define DEBUG_VIEW_NONE 0
#define DEBUG_VIEW_MATERIAL 1
#define DEBUG_VIEW_SHADOWS 2
#define DEBUG_VIEW_SSS 3
#define DEBUG_VIEW_SSAO 4
#define DEBUG_VIEW_VL 5
#define DEBUG_VIEW_RT 6
#define DEBUG_VIEW_ACCUMULATION 7
#define DEBUG_VIEW_SKY_IRRADIANCE 8
#define DEBUG_VIEW_SHADOWMAP_COLOR 9
#define DEBUG_VIEW_SHADOWMAP_NORMAL 10
#define DEBUG_VIEW_IRRADIANCE 11
#define DEBUG_VIEW_PARTICLES 12

#define DEBUG_MAT_ALBEDO 0
#define DEBUG_MAT_GEO_NORMAL 1
#define DEBUG_MAT_TEX_NORMAL 2
#define DEBUG_MAT_OCCLUSION 3
#define DEBUG_MAT_ROUGH 4
#define DEBUG_MAT_F0_METAL 5
#define DEBUG_MAT_POROSITY 6
#define DEBUG_MAT_SSS 7
#define DEBUG_MAT_EMISSION 8
#define DEBUG_MAT_LMCOORD 9
